- name: Install dependencies
  apt: name={{ item }} state=present
  become: yes
  with_items:
    - python
    - python-dev
    - python-virtualenv
    - gcc
    - dialog
    - libaugeas0
    - libssl-dev
    - libffi-dev
    - ca-certificates
    - python-pip
    - git
    - apt-transport-https
    - ca-certificates

- name: Get certbot
  become: yes
  get_url: url="https://dl.eff.org/certbot-auto" dest=/usr/bin

- name: Set certbot mode
  become: yes
  file: path=/usr/bin/certbot-auto mode=0750

- name: Ensure the well-known webroot dir exists
  become: yes
  file: path=/var/www/well-known state=directory mode=0755 owner=www-data group=www-data